# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET MAUI (Android)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
        
    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore HackerNewsApp2/HackerNewsApp2.csproj
      
    - name: Build MAUI Android
      run: dotnet publish HackerNewsApp2/HackerNewsApp2.csproj -c Release -f:net7.0-android --no-restore
      
    - name: Upload Android Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: hackernewsapp2-android-ci-build
        path: HackerNewsApp2/bin/Release/net7.0-android/*.apk*
  
  release:
    permissions:
      contents: write
    needs: build
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - name: github-action-release-apk
        uses: gogoadl/github-action-release-apk@v1.0.0-alpha09
        with:
          asset-name: 'Hacker-News-App.apk'
