name: .NET MAUI (Android)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
        
    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore HackerNewsApp2/HackerNewsApp2.csproj
      
    - name: Build MAUI Android
      run: dotnet publish HackerNewsApp2/HackerNewsApp2.csproj -c Release -f:net8.0-android34.0 --no-restore
      
    - name: Upload Android Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: hackernewsapp2-android-ci-build
        path: HackerNewsApp2/bin/Release/net8.0-android34.0/*.apk*
        
  release:
    permissions:
      contents: write
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - name: Create artifacts directory
        run: mkdir -p artifacts
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: hackernewsapp2-android-ci-build
          path: artifacts
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*.apk*
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
